# ----------------------------------------
# Production Database Override (PostgreSQL on Render)
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://dpg-d7538dlm5p6s73fg5h60-a.singapore-postgres.render.com/manageme_gng8
spring.datasource.username=${POSTGRES_DB_USERNAME}
spring.datasource.password=${POSTGRES_DB_PASSWORD}

# Tell Hibernate to use the Postgres dialect (NOTE: No comments allowed on this line!)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect